spring:
  mvc:
    locale-resolver: fixed
    locale: pt-br
  application:
    name: fisio-api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fisio_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: developer
    password: junior087
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /docs-fisio.html
  api-docs:
    path: /docs-fisio
  packagesToScan: com.ejunior.fisio_api.web.controllers